project:
  type: website
  output-dir: docs

website:
  title: "Your website name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Project Highlights
        menu:
          - text: Data Science
            href: data_visualizations.qmd
          - text: CS OR Other
            href: other_highlights.qmd
    right:
      - icon: envelope
        href: "mailto:your_email"
      - text: Linked
        icon: linkedin
        href: "https://www.linkedin.com/your_linkedin_address"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



